name: Generate trophy card

on:
  schedule:
    - cron: "0 */12 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: generate trophy.svg
        uses: soulteary/github-profile-trophy-action@v1.0.0
        with:
          options: 'username=${{ github.repository_owner }}&theme=dracula&row=1&margin-w=8&margin-h=8&no-bg=false&no-frame=false'
          path: dist/trophy.svg
          token: ${{ secrets.PAT_TOKEN || secrets.GITHUB_TOKEN }}

      - name: push trophy.svg to the output branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: trophy-output
